language: python
install: make && pip install coveralls
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  # PyPy versions
  - "pypy2.7"
  - "pypy3.5"
# command to install dependencies
script: coverage run --source topopy setup.py test
after_success:
  - coveralls